#!/usr/bin/env bash

interface=$1
event=$2

sentinel="/var/run/NetworkManager/brnet"
if [ -e /etc/default/brnet ] ; then
    . /etc/default/brnet
fi
export BRIDGE_USER NETDEV_GRP IF BRIDGE NUM_TAP FIRST_TAP

if [ -z "${BRNET}" ]; then
    BRNET="/usr/local/sbin/brnet-nmcli"
fi

if [ "$interface" == "${IF}" ]; then
    if [ "${event}" == "up" ] && [ ! -e "${sentinel}" ]; then
	touch "${sentinel}"
	${BRNET} start
    elif [ "${event}"  == "down" ] && [ -e "${sentinel}" ]; then
	${BRNET} stop
	rm -f "${sentinel}"
    fi
fi
